# PlatformIO pre-build script: derive the firmware version from the release tag instead of a hand-bumped #define.
#
#   extra_scripts = pre:lib/dustlib/scripts/fw_version.py
#   #include <fw_version.h>   // FW_VERSION, e.g. "1.3" or "1.3+4.ge23434b.dirty"
#
# Source of truth, in order:
#   1. $FW_VERSION (CI sets it from the pushed fw-v<version> tag)
#   2. git describe --match 'fw-v*': on a tag that's the tag's version; N commits past it becomes
#      "<version>+<N>.g<sha>" (semver build metadata, so it compares equal to the tag it grew from and the
#      updater neither nags nor claims it's newer); "+dirty" / ".dirty" marks uncommitted changes
#   3. "0.0.0+g<sha>[.dirty]" in a repo with no fw-v tag yet, "0.0.0+unknown" outside git
# The result never contains whitespace: it's a token in the IDENTIFY response.
#
# The header is written to the build dir and only rewritten when the version changes, so a new commit recompiles
# just the files that include it rather than the whole project (which a -D flag would).
import os
import re
import subprocess

Import("env")

TAG_PREFIX = "fw-v"


def git(project_dir, *args):
    try:
        return subprocess.check_output(["git", *args], cwd=project_dir, stderr=subprocess.DEVNULL, text=True).strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def git_version(project_dir):
    desc = git(project_dir, "describe", "--tags", "--match", TAG_PREFIX + "*", "--long", "--dirty")
    m = desc and re.fullmatch(re.escape(TAG_PREFIX) + r"(.+)-(\d+)-(g[0-9a-f]+)(-dirty)?", desc)
    if not m:
        sha = git(project_dir, "describe", "--always", "--abbrev=7", "--dirty=.dirty", "--exclude=*")
        return "0.0.0+g" + sha if sha else None
    version, distance, sha, dirty = m.groups()
    meta = [] if distance == "0" else [distance, sha]
    if dirty:
        meta.append("dirty")
    return version + ("+" + ".".join(meta) if meta else "")


version = (os.environ.get("FW_VERSION") or "").strip() or git_version(env.subst("$PROJECT_DIR")) or "0.0.0+unknown"
version = re.sub(r"\s+", "", version)
if version.startswith(TAG_PREFIX):
    version = version[len(TAG_PREFIX):]

gen_dir = os.path.join(env.subst("$BUILD_DIR"), "fw_version")
os.makedirs(gen_dir, exist_ok=True)
header = os.path.join(gen_dir, "fw_version.h")
content = ("// generated by dustlib/scripts/fw_version.py -- do not edit\n"
           "#pragma once\n#define FW_VERSION \"%s\"\n" % version)
try:
    with open(header) as f:
        stale = f.read() != content
except OSError:
    stale = True
if stale:
    with open(header, "w") as f:
        f.write(content)
env.Append(CPPPATH=[gen_dir])
print("FW_VERSION %s" % version)
